apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "file-write"
spec:
  kprobes:
  - call: "nfs_file_open"
    message: "File Write Event"
    syscall: false
    args:
    - index: 1
      type: "file" # (struct file *) used for getting the path
    selectors:
    - matchBinaries:
      - operator: "In"
        values:
        - "/usr/bin/kubelet"
    - matchArgs:
      - index: 1
        operator: "Prefix"
        values:
        - "/var/lib/kubelet/pods"
    tags: [ "observability.filesystem", "observability.process" ]
