apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "volume-init"
spec:
  kprobes:
  - call: "nfs4_submount"
    message: "init nfs volume"
    syscall: false
#    args:
#    - index: 1
#      type: "file" # (struct file *) used to get file path
#    selectors:
#    - matchBinaries:
#      - operator: "In"
#        values:
#        - "/usr/bin/kubelet"
#    - matchArgs:
#      - index: 1
#        operator: "Prefix"
#        values:
#        - "/share"
    tags: [ "observability.filesystem", "observability.process" ]
