# For Kube-proxy Free Setting.
kubeProxyReplacement: true
k8sServiceHost: "192.168.20.11"
k8sServicePort: 6443
#---------------------------------------------------------------------------------

# Routing Mode Configure
# REF: https://docs.cilium.io/en/stable/network/concepts/routing
routingMode: "native"
autoDirectNodeRoutes: true

# This only handle pod's IP, not work with svc, etc...
# Service'IP depends on kubernetes config(service-cluster-ip-range)
ipam:
  mode: "cluster-pool"
  operator:
    clusterPoolIPv4PodCIDRList: ["10.2.0.0/16"]
    clusterPoolIPv4MaskSize: 24

ipv4NativeRoutingCIDR: "10.2.0.0/16"
enableIPv4Masquerade: true
bpf:
  masquerade: true

#---------------------------------------------------------------------------------

# Cilium As Ingress Controller Setting - Not working when using host network mode (v.1.16.6)
l7Proxy: true
ingressController:
  enabled: true
  default: true # Set Cilium as Default Ingress Controller
  loadbalancerMode: "dedicated"
#
#  # Create Shared Controller
#  #loadbalancerMode: "shared"
#  #sharedListenerPort: 8080  # Default=8080
#  
#  # Create Controller Per Ingress
#  loadbalancerMode: "dedicated"
#  # UNCOMMENT THIS WHEN "hostNetwork.enabled=true"
#  service:
#    type: ClusterIP
#    externalTrafficPolicy: Null
#  
#  # If hostNetwork.enabled == true, Service Type NodePort/Loadbalancer will be disabled.
#  hostNetwork:
#    enabled: true
#---------------------------------------------------------------------------------

# Cilium Gateway API Setting
gatewayAPI:
  enabled: true
#  hostNetwork:
#    enabled: true
l7Proxy: true
nodePort:
  enabled: true
endpointRoutes:
  enabled: true
#--------------------------------------------------------------------------------------

# Hubble Setting
hubble:
  enabled: true 
  relay:
    enabled: true
  ui:
    enabled: true
  # REF: https://docs.cilium.io/en/latest/observability/hubble/configuration/export/
  #  export:
  #    static:
  #      enabled: true # Set true to enable static log exporter
  #      filePath: "/var/run/cilium/hubble/events.log"
  #    dynamic:
  #      enabled: false # For Safety
  #    fileMaxSizeMb: 10 # Default = 10
  #    fileMaxBackups: 5 # Default = 5
  # https://docs.cilium.io/en/stable/observability/grafana/
  metrics:
    enableOpenMetrics: true
      #    serviceMonitor:
      #      enabled: true
      #    dashboards:
      #      enabled: true
      #      namespace: monitoring
      #      annotations:
      #        grafana_folder: "Hubble"
    enabled: 
    - dns:query;ignoreAAAA
    - drop #:sourceContext=identity;destinationContext=identity
    - tcp
    - flow
    - port-distribution
    - icmp
    # Enable additional labels for L7 flows
    - httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction
#--------------------------------------------------------------------------------------

# Prometheus
prometheus:
  enabled: true
operator:
  prometheus:
    enabled: true
#--------------------------------------------------------------------------------------

# Mutual Authentication (Beta Feature at v1.16)
#authentication:
#  mutual:
#    spire:
#      enabled: false
#      install:
#        enabled: true
#--------------------------------------------------------------------------------------

# Host Firewall
hostFirewall:
  enabled: true
#--------------------------------------------------------------------------------------

# L2 Announcements / L2 Aware LB (Beta Feature at v1.17)
# Ensure that value below are declared:
# kubeProxyReplacement = true
# k8sServiceHost=${API_SERVER_IP}
# k8sServicePort=${API_SERVER_PORT}

l2announcements:
  enabled: true
k8sClientRateLimit:
  qps: 30 # num(services) * (1 / leaseRenewDeadline)
  burst: 50 # slightly higher to allow for bursts of traffic
#--------------------------------------------------------------------------------------

# Transparent Encryption
#encryption:
#  enabled: true
#  type: "wireguard"

#--------------------------------------------------------------------------------------
