apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "tracing-fd"
spec:
  kprobes:
  - call: "security_file_permission"
    syscall: false
    return: true
    args:
    - index: 0
      type: "file"
    - index: 1
      type: "int"
    returnArg:
      index: 0
      type: "int"
    selectors:
    - matchArgs:
      - index: 0
        operator: "Equal"
        values:
        - "/etc/passwd"
      - index: 1
        operator: "Equal"
        values:
        - "2"
    - matchActions:
      - action: Override
        argError: -1
