prometheus:
  prometheusSpec:
    additionalScrapeConfigsSecret:
      enabled: true
      name: additional-scrape-configs
      key: prometheus-additional.yaml
    # Refer: https://tetragon.io/docs/installation/metrics/#enable-prometheus-servicemonitors
    serviceMonitorSelectorNilUsesHelmValues: false

grafana:
  enabled: true
  adminPassword: netAi007!
  persistence:
    enabled: true
    type: pvc
    storageClassName: "nfs-csi"
    accessModes:
      - ReadWriteOnce
    size: 20Gi
    finalizers:
      - kubernetes.io/pvc-protection


