apiVersion: cilium.io/v1alpha1
kind: TracingPolicyNamespaced
metadata:
  name: prevent-shell-execution
  namespace: workspace-s
spec:
  # podSelector:
  #   matchLabels:
  #   matchExpressions:
  # 이 방식을 활용할 경우, sh에 한하여 Block이 불가능;
  tracepoints:
  - subsystem: "sched"
    event: "sched_process_exec"
    args:
    - index: 0
      type: "int"
      resolve: "pid"
    - index: 2
      type: "linux_binprm"
    selectors:
    - matchBinaries:
      - operator: "In"
        values:
        - "/bin/sh"
        - "/bin/bash"
        - "/usr/bin/sh"
        - "/usr/bin/bash"
      matchActions:
      - action: Sigkill
 
