apiVersion: cilium.io/v1alpha1
kind: TracingPolicyNamespaced
metadata:
  name: "fd-install-logger"
  namespace: "playground"
spec:
  kprobes:
  - call: "fd_install"
    syscall: false
    args:
    - index: 0
      type: int
    - index: 1
      type: file
    selectors:
    - matchPIDs:
      - operator: NotIn
        followForks: false
        isNamespacePID: true
        values: [1]
      matchBinaries:
      - operator: "NotPostfix"
        values:
        - "tetragon"
      matchArgs:
      - index: 1
        operator: Prefix
        values:
        - /home
