apiVersion: cilium.io/v1alpha1
kind: TracingPolicyNamespaced
metadata:
  name: "file-open"
  namespace: "playground"
  labels:
    tracing-method: internal-kernel
spec:
  kprobes:
  - call: "fd_install"
    syscall: false
    args:
    - index: 0
      type: int
    - index: 1
      type: file
    selectors:
    - matchPIDs:
      - operator: NotIn
        # followForks: true
        isNamespacePID: true
        values:
        - 0
        - 1
      matchArgs:
      - index: 1
        operator: "Prefix"
        values:
        - "/nfs-vol"
      matchActions:
      - action: FollowFD
        argFd: 0
        argName: 1
---
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
kind: TracingPolicyNamespaced
metadata:
  name: "file-close"
  namespace: "playground"
spec:
  kprobes:
  - call: "sys_close"
    syscall: true
    args:
    - index: 0
      type: int
    selectors:
    - matchPIDs:
      - operator: NotIn
       # followForks: true
        isNamespacePID: true
        values:
        - 0
        - 1
      matchActions:
      - action: UnfollowFD
        argFd: 0
