apiVersion: cilium.io/v1alpha1
kind: TracingPolicyNamespaced
metadata:
  name: "file-access"
  namespace: "playground"
  labels:
    tracing-method: lsm
spec:
  kprobes:
  - call: "security_file_permission"
    syscall: false
    args:
    - index: 0
      type: file
    - index: 0
      type: int

