apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "file-access"
  labels:
    tracing-method: lsm
spec:
  lsmhooks:
  - hook: "file_permission"
    args:
    - index: 0
      type: file
    - index: 1
      type: int
      label: mask
    selectors:
    - matchArgs:
      - index: 0
        operator: "Prefix"
        values:
        - "/home/s6"

