apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "file-open"
  labels:
    tracing-method: internal-kernel
spec:
  kprobes:
  - call: "fd_install"
    syscall: false
    args:
    - index: 0
      type: int
    - index: 1
      type: file
    selectors:
    - matchPIDs:
      - operator: NotIn
        values:
        - 0
        - 1
      matchArgs:
      - index: 1
        operator: "Prefix"
        values:
        - "/nfs-vol"

