tetragon:
  prometheus:
    serviceMonitor:
      enabled: true
tetragonOperator:
  prometheus:
    serviceMonitor:
      enabled: true
rthooks:
  enabled: true
  interface: nri-hook
  failAllowNamespaces: "default,playground"
