apiVersion: v1
kind: Pod
metadata:
  name: test-pod-temp
  namespace: playground
  labels:
    app: test-pod
    purpose: playground
spec:
  containers:
  - name: play-pod-temp
    image: tori209/test-image:0.2
    # imagePullPolicy: Never
    resources: {}
    command: ["/bin/bash", "-c", "while true; do sleep 1000; done"]
    ports:
    - containerPort: 80
  nodeName: s3
