apiVersion: v1
kind: Pod
metadata:
  name: test-pod-deploy
  namespace: playground
  labels:
    app: test-pod
    purpose: playground
spec:
  containers:
  - name: busybox-container
    image: busybox:latest
    # imagePullPolicy: Never
    resources:
      requests:
        cpu: 30m
        memory: 64Mi
      limits:
        cpu: 30m
        memory: 128Mi
    command: ["/bin/sh", "-c", "--", "while true; do sleep 1000; done"]
    ports:
    - containerPort: 80
  nodeName: s6
