apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pod-pvc
  namespace: playground
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-with-pvc
  namespace: playground
  labels:
    app: test-pod
    purpose: playground
spec:
  containers:
  - name: play-pod
    image: nginx:latest
    # imagePullPolicy: Never
    resources: {}
      #command: ["/bin/bash", "-c"]
      #args:
      #- "chown 1000:1000 /share;" # while true; do sleep 1000; done"
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-data
      mountPath: /share
  volumes:
  - name: shared-data
    persistentVolumeClaim:
      claimName: test-pod-pvc
  nodeName: s6

