apiVersion: v1
kind: Pod
metadata:
  name: test-pod-0
  namespace: playground
  labels:
    app: test-pod
    purpose: playground
spec:
  containers:
  - name: play-pod
    image: nginx:1.15.9
    # imagePullPolicy: Never
    resources: {}
    command: ["/bin/bash", "-c", "while true; do sleep 1000; done"]
    ports:
    - containerPort: 80
  nodeName: s6
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-1
  namespace: playground
  labels:
    app: test-pod
    purpose: playground
spec:
  containers:
  - name: play-pod
    image: nginx:1.15.9
    # imagePullPolicy: Never
    resources: {}
    command: ["/bin/bash", "-c", "while true; do sleep 1000; done"]
    ports:
    - containerPort: 80
  nodeName: s6
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-2
  namespace: playground
  labels:
    app: test-pod
    purpose: playground
spec:
  containers:
  - name: play-pod
    image: nginx:1.15.9
    # imagePullPolicy: Never
    resources: {}
    command: ["/bin/bash", "-c", "while true; do sleep 1000; done"]
    ports:
    - containerPort: 80
  nodeName: s5
